### ISSUE TITLE
No feedback link in Welsh translation

### ISSUE THREAD

**Issue by sarrionandia** [communitiesuk/epb-frontend#46]
<img width="677" alt="Screenshot 2020-12-21 at 15 20 57" src="https://user-images.githubusercontent.com/507292/102792251-2a64a780-43a0-11eb-818a-08903ab67cd7.png">

**Comment by TheDoubleK** [comment]
Link has been added - the feedback form is still in English only, but we have a ticket on the backlog to make a separate Welsh language form.
